import Vue from 'vue';
import Vuetify, {
  VApp,
  VNavigationDrawer,
  VFooter,
  VToolbar,
  VMenu,
  VIcon,
  VRadioGroup,
  VSnackbar,
  VCard,
  VTextField,
  VDataTable,
  VDivider,
  VDialog,
  VAlert,
  VBtn,
  VList,
  VListGroup,
  VListTile,
  VListTileContent,
  VListTileTitle,
  VTooltip,
  VPagination,
  VDataIterator,
  VExpansionPanel,
} from 'vuetify/lib';
import 'vuetify/src/stylus/app.styl';
import zhHant from 'vuetify/es5/locale/zh-Hant';

Vue.use(Vuetify, {
  components: {
    VApp,
    VNavigationDrawer,
    VFooter,
    VToolbar,
    VMenu,
    VIcon,
    VRadioGroup,
    VSnackbar,
    VCard,
    VTextField,
    VDataTable,
    VDivider,
    VDialog,
    VAlert,
    VBtn,
    VList,
    VListGroup,
    VListTile,
    VListTileContent,
    VListTileTitle,
    VTooltip,
    VPagination,
    VDataIterator,
    VExpansionPanel,
  },
  theme: {
    primary: '#2F599C',
    secondary: '#142952',
    accent: '#C4E4EE',
    textBlack: '#231815',
    error: '#E96143',
    info: '#41BBD6',
    success: '#94BF80',
    F6B42C: '#FFC107',
  },
  options: {
    customProperties: true,
  },
  iconfont: 'mdi',
  lang: {
    locales: { zhHant },
    current: 'zhHant',
  },
  breakpoint: {
    thresholds: {
      xs: 360,
      sm: 600,
      md: 1080,
      lg: 3680,
    },
    scrollbarWidth: 10,
  },
});
